application: omarresume version: 1 runtime: python27 api_version: 1 threadsafe: yes
handlers:
- url: /(.*\.html) static_files: static/\1 upload: static/(.*)
- url: / static_files: static/index.html upload: static/index.html 
- url: /styles/(.*) static_files: static/styles/\1 upload: static/styles/(.*) 
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: static/\1
  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png))